### ISSUE TITLE
1.2 Runtime FW Release Checklist

### ISSUE THREAD

**Issue by nquarton** [chipsalliance/caliptra-sw#1839]
- [ ] Manifest-based auth update https://github.com/chipsalliance/caliptra-sw/pull/1828
- [ ] DPE export CDI https://github.com/chipsalliance/caliptra-sw/issues/1807
- [ ] Increase DPE max cert size to 6k https://github.com/chipsalliance/caliptra-sw/issues/1832
- [ ] Stack overflow fixes
- [ ] FMC Alias CSR https://github.com/chipsalliance/caliptra-sw/issues/1837
